connection handler failed
Traceback (most recent call last):
  File "/root/miniconda3/envs/photo/lib/python3.12/site-packages/websockets/asyncio/server.py", line 373, in conn_handler
    await self.handler(connection)
  File "/root/test_celery/server.py", line 157, in handle_client
    await websocket.send(error_message)
  File "/root/miniconda3/envs/photo/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 458, in send
    async with self.send_context():
               ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/photo/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/photo/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 933, in send_context
    raise self.protocol.close_exc from original_exc
websockets.exceptions.ConnectionClosedError: no close frame received or sent
